import type { HealthRecord, Metric } from './shared/types';

export const labels: Record<Metric, string> = { weight: 'Weight', heartRate: 'Heart rate', restingHeartRate: 'Resting heart rate', bloodPressureSystolic: 'Blood pressure (systolic)', bloodPressureDiastolic: 'Blood pressure (diastolic)', bodyTemperature: 'Body temperature', steps: 'Steps', activeEnergy: 'Active energy', exerciseTime: 'Exercise time', distance: 'Walking / running distance', flights: 'Flights climbed', sleep: 'Sleep', walkingSpeed: 'Walking speed', stepLength: 'Step length', walkingAsymmetry: 'Walking asymmetry', doubleSupport: 'Double support', stairAscentSpeed: 'Stair ascent speed', stairDescentSpeed: 'Stair descent speed', sixMinuteWalk: 'Six-minute walk', medication: 'Medication' };
export const metricGroups: { title: string; metrics: Metric[] }[] = [
  { title: 'Vitals', metrics: ['weight', 'heartRate', 'restingHeartRate', 'bloodPressureSystolic', 'bloodPressureDiastolic', 'bodyTemperature'] },
  { title: 'Sleep & activity', metrics: ['sleep', 'steps', 'activeEnergy', 'exerciseTime', 'distance', 'flights'] },
  { title: 'Mobility', metrics: ['walkingSpeed', 'stepLength', 'walkingAsymmetry', 'doubleSupport', 'stairAscentSpeed', 'stairDescentSpeed', 'sixMinuteWalk'] }
];
export function filtered(records: HealthRecord[], from: string, to: string) { return records.filter((r) => (!from || r.date >= `${from}T00:00:00`) && (!to || r.date <= `${to}T23:59:59.999Z`)); }
export function latest(records: HealthRecord[], metric: Metric) { return records.filter((r) => r.metric === metric).at(-1); }
export function daily(records: HealthRecord[], metric: Metric) { const map = new Map<string, { total: number; count: number; unit: string }>(); records.filter((r) => r.metric === metric).forEach((r) => { const day = r.date.slice(0, 10); const current = map.get(day) ?? { total: 0, count: 0, unit: r.unit }; current.total += r.value; current.count++; map.set(day, current); }); return [...map].map(([date, d]) => ({ date, value: d.total / d.count, unit: d.unit })); }
export interface DailyStats { date: string; values: number[]; unit: string; min: number; max: number; average: number; standardDeviation: number; }
export function dailyStats(records: HealthRecord[], metric: Metric): DailyStats[] { const groups = new Map<string, HealthRecord[]>(); records.filter((record) => record.metric === metric).forEach((record) => { const day = record.date.slice(0, 10); groups.set(day, [...(groups.get(day) ?? []), record]); }); return [...groups].map(([date, rows]) => { const values = rows.slice().sort((a, b) => a.date.localeCompare(b.date)).map((row) => row.value); const average = values.reduce((sum, value) => sum + value, 0) / values.length; const standardDeviation = Math.sqrt(values.reduce((sum, value) => sum + (value - average) ** 2, 0) / values.length); return { date, values, unit: rows[0].unit, min: Math.min(...values), max: Math.max(...values), average, standardDeviation }; }).sort((a, b) => b.date.localeCompare(a.date)); }
export function format(value: number, unit = '') { return `${new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 }).format(value)}${unit ? ` ${unit}` : ''}`; }
